import { describe, expect, it } from 'vitest';
import { diagnoseSession, ingest } from '@swinglab/core';
import { SAMPLE_SESSIONS, isSampleSession, SAMPLE_PREFIX } from './sample.js';

/**
 * The demo is the first thing every new person sees, and it is a 23KB string
 * literal generated by a script.
 *
 * That is a combination worth a test. Backticks, backslashes and `${` inside
 * the CSV all have to survive being embedded in a template literal, and if
 * the escaping breaks there is no crash — the parser simply finds no shots
 * and a tester lands on an empty screen with a note about a file they never
 * chose. Nothing else in the build would notice.
 */
describe('the bundled sample history', () => {
  it('ships five sessions', () => {
    expect(SAMPLE_SESSIONS).toHaveLength(5);
  });

  it('parses every one of them into shots', () => {
    for (const input of SAMPLE_SESSIONS) {
      const result = ingest(input, { handedness: 'right' });
      expect(result.session, `${input.name} produced no session`).not.toBeNull();
      expect(result.session!.shots.length).toBeGreaterThan(15);
    }
  });

  it('is recognisable as sample data after a reload', () => {
    // The marker lives in the filename, which is what storage keeps.
    for (const input of SAMPLE_SESSIONS) {
      expect(input.name.startsWith(SAMPLE_PREFIX)).toBe(true);
      const session = ingest(input, { handedness: 'right' }).session!;
      expect(isSampleSession(session.sourceRef)).toBe(true);
    }
  });

  it('does not mistake a real export for sample data', () => {
    expect(isSampleSession('Normalized_2.Normalized.csv')).toBe(false);
    expect(isSampleSession('my range session.csv')).toBe(false);
  });

  it('spans enough weeks for the trend lines to draw', () => {
    /*
     * The reason there are five and not one. A single session leaves Trends
     * saying "import 2 more sessions", which is a locked door in the middle
     * of the tour.
     */
    const dates = SAMPLE_SESSIONS
      .map((s) => ingest(s, { handedness: 'right' }).session!.startedAt)
      .filter((d): d is Date => d instanceof Date)
      .sort((a, b) => a.getTime() - b.getTime());
    expect(dates.length).toBeGreaterThanOrEqual(3);
    const weeks = (dates.at(-1)!.getTime() - dates[0]!.getTime()) / (7 * 86_400_000);
    expect(weeks).toBeGreaterThan(3);
  });

  it('is a session with something wrong in it, so the app has something to say', () => {
    // A flawless demo shows off none of the machinery.
    const newest = SAMPLE_SESSIONS.at(-1)!;
    const report = diagnoseSession(ingest(newest, { handedness: 'right' }).session!);
    expect(report.findings.length).toBeGreaterThan(2);
    expect(report.practice.blocks.length).toBeGreaterThan(0);
    expect(report.clubsSeen.length).toBeGreaterThanOrEqual(3);
  });
});
